### ISSUE TITLE
Support polymorphic serialization

### ISSUE THREAD

**Issue by BenWoodworth** [BenWoodworth/knbt#13]
If you have any use cases please drop them here!

I'm pretty busy and not even sure polymorphic serialization is needed for NBT so unless there's a need for it I probably won't get around to it for a while

**Comment by WinX64** [comment]
Perhaps now is a good time. 23w40a just changed it so [Chat Components are serialized as NBT](https://minecraft.wiki/w/Java_Edition_23w40a#General_2) instead of JSON when sent over the network.

Support for polymorphism would help handling the different types of components, just like it's usually done with JSON (content-based polymorphism in this case).

**Comment by Ayfri** [comment]
Any update ?

**Comment by BenWoodworth** [comment]
Just pushed this out in v0.11.4! :)
